---
- name: Setup my macOS
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - {role: homebrew,      tags: [homebrew]}
    - {role: homebrew-cask, tags: [homebrew-cask]}
    - {role: mac-app-store, tags: [mac-app-store]}
    - {role: atom,          tags: [atom]}
    #- {role: fish-shell,    tags: [fish-shell]}
